### ISSUE TITLE
Function name problem in In artifact_detection.py

### ISSUE THREAD

**Issue by 201210302** [TencentARC/DeSRA#5]
In artifact_detection.py
I think 
Line 10 "from mmseg.apis import **inference_segmentor, init_segmentor, show_seg from mmseg.apis import inference_model, init_model, show_result_pyplot**" should be change to 
"from mmseg.apis import **inference_model, init_model, show_result_pyplot from mmseg.core.evaluation import get_palette"**
because of function name in mmsegmentation.

What is your opinion on my thoughts?

**Comment by LiangbinXie** [comment]
Since there has been a significant change in mmsegmentation (including function names, etc.) after this work, the code is not compatible with the latest version of mmsegmentation. I have not specifically adapted to the new version of mmsegmentation, so I am not sure whether the results obtained in this way are consistent with the results of the 0.29.0 version I used. If this method can be adapted to the new version, I can make corresponding modifications later.
